---
- name: "Storage / AutoFS / Initialize"
  ansible.builtin.include_tasks:
    file: "stg_autofs_initialize.yml"

- name: "Storage / AutoFS / Prepare"
  ansible.builtin.include_tasks:
    file: "stg_autofs_prepare.yml"
  when:
    - stg_autofs['prepare'] is defined
    - stg_autofs['prepare']

- name: "Storage / AutoFS / Deploy"
  ansible.builtin.include_tasks:
    file: "stg_autofs_deploy.yml"
  when:
    - stg_autofs['deploy'] is defined
    - stg_autofs['deploy']

- name: "Storage / AutoFS / Setup"
  ansible.builtin.include_tasks:
    file: "stg_autofs_setup.yml"
  when:
    - stg_autofs['setup'] is defined
    - stg_autofs['setup']

- name: "Storage / AutoFS / Control"
  ansible.builtin.include_tasks:
    file: "stg_autofs_control.yml"
  when:
    - stg_autofs['control'] is defined
    - stg_autofs['control']

- name: "Storage / AutoFS / Provision"
  ansible.builtin.include_tasks:
    file: "stg_autofs_provision.yml"
  when:
    - stg_autofs['provision'] is defined
    - stg_autofs['provision']

- name: "Storage / AutoFS / Finalize"
  ansible.builtin.include_tasks:
    file: "stg_autofs_finalize.yml"
...
