---
- name: "Storage / AutoFS / Provision / Maps"
  ansible.builtin.include_tasks:
    file: "stg_autofs_provision_maps.yml"
  loop: "{{ stg_autofs_maps }}"
  loop_control:
    loop_var: "stg_autofs___provision_map"
  when:
    - stg_autofs_maps is defined
    - stg_autofs_maps | length > 0
...
