---
- name: "Storage / AutoFS / Provision / Maps / Create mount"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ stg_autofs_base['paths']['root'] + '/' + stg_autofs___provision_map['mount'] }}"
    owner: "{{ stg_autofs_base['access']['user']['owner'] }}"
    group: "{{ stg_autofs_base['access']['group']['owner'] }}"
    mode: "{{ stg_autofs_base['access']['mode']['dir'] }}"

- name: "Storage / AutoFS / Provision / Maps / Set custom map ({{
    stg_autofs___provision_map['name'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ stg_autofs_base['access']['user']['owner'] }}"
    group: "{{ stg_autofs_base['access']['group']['owner'] }}"
    mode: "{{ stg_autofs_base['access']['mode']['file'] }}"
    src: "{{ stg_autofs_base['templates']['custom_autofs'] }}"
    dest: "{{
      stg_autofs_base['paths']['auto_master_d'] + '/' +
      stg_autofs___provision_map['name'] + '.autofs'
      }}"

- name: "Storage / AutoFS / Provision / Maps / Set custom map definition ({{
    stg_autofs___provision_map['name'] }})"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ stg_autofs_base['access']['user']['owner'] }}"
    group: "{{ stg_autofs_base['access']['group']['owner'] }}"
    mode: "{{ stg_autofs_base['access']['mode']['file'] }}"
    src: "{{ stg_autofs_base['templates']['auto_custom'] }}"
    dest: "{{
      stg_autofs_base['paths']['auto_custom_d'] + '/' +
      'auto.' + stg_autofs___provision_map['name']
      }}"
...
