---
- name: "Storage / AutoFS / Setup / Server / Set Configuration Repositories"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "directory"
    path: "{{ stg_autofs___setup_path }}"
    owner: "{{ stg_autofs_base['access']['user']['owner'] }}"
    group: "{{ stg_autofs_base['access']['group']['owner'] }}"
    mode: "{{ stg_autofs_base['access']['mode']['dir'] }}"
  loop:
    - "{{ stg_autofs_base['paths']['auto_master_d'] }}"
    - "{{ stg_autofs_base['paths']['auto_custom_d'] }}"
  loop_control:
    loop_var: stg_autofs___setup_path

- name: "Storage / AutoFS / Setup / Server / Remove Defaults"
  become: true
  ansible.builtin.file:
    follow: false
    unsafe_writes: false
    force: false
    state: "absent"
    path: "{{ stg_autofs___setup_file }}"
  loop:
    - "{{ stg_autofs_base['etc']['auto_net'] }}"
    - "{{ stg_autofs_base['etc']['auto_misc'] }}"
    - "{{ stg_autofs_base['etc']['auto_smb'] }}"
  loop_control:
    loop_var: stg_autofs___setup_file

- name: "Storage / AutoFS / Setup / Server / Set Configuration"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ stg_autofs_base['access']['user']['owner'] }}"
    group: "{{ stg_autofs_base['access']['group']['owner'] }}"
    mode: "{{ stg_autofs_base['access']['mode']['file'] }}"
    src: "{{ stg_autofs_base['templates']['autofs_conf'] }}"
    dest: "{{ stg_autofs_base['etc']['autofs_conf'] }}"

- name: "Storage / AutoFS / Setup / Server / Set Auto Master Definition"
  become: true
  ansible.builtin.template:
    backup: false
    follow: false
    force: true
    unsafe_writes: false
    owner: "{{ stg_autofs_base['access']['user']['owner'] }}"
    group: "{{ stg_autofs_base['access']['group']['owner'] }}"
    mode: "{{ stg_autofs_base['access']['mode']['file'] }}"
    src: "{{ stg_autofs_base['templates']['auto_master'] }}"
    dest: "{{ stg_autofs_base['etc']['auto_master'] }}"
...
