---
- name: "Storage / AutoFS / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ stg_autofs_application }}"
    sys_package_profiles: "{{ stg_autofs_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
