---
- name: "Storage / AutoFS / Control / Subsystem / Set state (service: {{
    stg_autofs_subsystem_profile['service'] }})"
  become: true
  ansible.builtin.systemd:
    no_block: false
    scope: "system"
    name: "{{ stg_autofs_subsystem_profile['service'] }}"
    state: "{{
      stg_autofs_subsystem_profile['states']
      [stg_autofs_subsystem['status']]
      }}"
...
