---
- name: "Storage / AutoFS / Control / Subsystem / Set enabled state (service: {{
    stg_autofs_subsystem_profile['service'] }})"
  become: true
  ansible.builtin.systemd:
    no_block: false
    scope: "system"
    name: "{{ stg_autofs_subsystem_profile['service'] }}"
    enabled: "{{ stg_autofs_subsystem['enabled'] }}"
...
