---
- name: "Storage / AutoFS / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in stg_autofs_platforms

- name: "Storage / AutoFS / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + stg_autofs_os_family + '.yml' }}"

- name: "Storage / AutoFS / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "stg_autofs_prerequisite.yml"
  when:
    - "'resolve_prereq' in stg_autofs"
    - stg_autofs['resolve_prereq']
...
