---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision"
      vars:
        stg_autofs:
          provision: true
        stg_autofs_maps:
          - name: "test"
            mount: "test"
            shares:
              - source: "test_source"
                target: "test_target"
                options: "ro"
      ansible.builtin.include_role:
        name: "stg_autofs"
...
