---
namespace: "serdigital64"
name: "storage"
version: "1.3.0"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating storage management"
license:
  - "GPL-3.0-or-later"
tags:
  - "storage"
dependencies:
  ansible.posix: "*"
  serdigital64.backup: "*"
  serdigital64.system: "*"
  serdigital64.security: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
