---
- name: "Storage / NFS / Server / Initialize"
  ansible.builtin.include_tasks:
    file: "stg_nfs_server_initialize.yml"

- name: "Storage / NFS / Server / Deploy"
  ansible.builtin.include_tasks:
    file: "stg_nfs_server_deploy.yml"
  when:
    - stg_nfs_server['deploy'] is defined
    - stg_nfs_server['deploy']

- name: "Storage / NFS / Server / Setup"
  ansible.builtin.include_tasks:
    file: "stg_nfs_server_setup.yml"
  when:
    - stg_nfs_server['setup'] is defined
    - stg_nfs_server['setup']

- name: "Storage / NFS / Server / Control"
  ansible.builtin.include_tasks:
    file: "stg_nfs_server_control.yml"
  when:
    - stg_nfs_server['control'] is defined
    - stg_nfs_server['control']

- name: "Storage / NFS / Server / Provision"
  ansible.builtin.include_tasks:
    file: "stg_nfs_server_provision.yml"
  when:
    - stg_nfs_server['provision'] is defined
    - stg_nfs_server['provision']

- name: "Storage / NFS / Server / Finalize"
  ansible.builtin.include_tasks:
    file: "stg_nfs_server_finalize.yml"
...
