---
- name: "Storage / NFS / Server / Control / Subsystem / Set state (service: {{
    stg_nfs_server_subsystem_profile['service'] }})"
  become: true
  ansible.builtin.systemd:
    no_block: false
    scope: "system"
    name: "{{ stg_nfs_server_subsystem_profile['service'] }}"
    state: "{{
      stg_nfs_server_subsystem_profile['states']
      [stg_nfs_server_subsystem['status']]
      }}"
...
