---
- name: "Storage / NFS / Server / Deploy / Package / Provision application"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ stg_nfs_server_application }}"
    sys_package_profiles: "{{ stg_nfs_server_profiles }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
