---
# Define platform specific paths
stg_nfs_server_base:
  paths: "{{ stg_nfs_server_base_common['paths'] }}"
  files: "{{ stg_nfs_server_base_common['files'] }}"
  run: "{{ stg_nfs_server_base_common['run'] }}"
  etc: "{{ stg_nfs_server_base_common['etc'] }}"
  templates: "{{ stg_nfs_server_base_common['templates'] }}"
  access: "{{ stg_nfs_server_base_common['access'] }}"

# Define application package details
stg_nfs_server_profiles:
  snap: "{{ stg_nfs_server_profiles_common['snap'] }}"
  flatpak: "{{ stg_nfs_server_profiles_common['flatpak'] }}"
  distro:
    latest:
      supported: true
      packages:
        - name: "nfs-utils"

# Define custom package repositories
stg_nfs_server_repository_custom_yum: []
stg_nfs_server_repository_custom_apt: []

# Set package repositories states
stg_nfs_server_repository_catalog_distro: {}
stg_nfs_server_repository_catalog_yum: {}
stg_nfs_server_repository_catalog_apt: {}

# Define OS subsystem states
stg_nfs_server_subsystem_profile:
  service: "nfs-server"
  states:
    started: "started"
    stopped: "stopped"
    refreshed: "refreshed"
...
