---
galaxy_info:
  role_name: "stg_autofs"
  author: "serdigital64"
  description: "Manage the AutoFS service"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "autofs"
dependencies: []
...
