---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Control service"
      vars:
        stg_nfs_server:
          control: true
        stg_nfs_server_subsystem: "{{ test_stg_nfs_server_subsystem }}"
      ansible.builtin.include_role:
        name: "stg_nfs_server"
...
