---
- name: "Prepare"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"


    - name: "Deploy required packages"
      vars:
        stg_nfs_server:
          resolve_prereq: true
          deploy: true
      ansible.builtin.include_role:
        name: "stg_nfs_server"

    - name: "Deploy firewall"
      vars:
        sec_firewall_os:
          deploy: true
          setup: true
          control: true
        sec_firewall_os_subsystem:
          enabled: true
          status: "started"
      ansible.builtin.include_role:
        name: "serdigital64.system.sys_package"
...
