---
stg_nfs_server_application:
  name: "nfs_server"
  type: "distro"
  version: "latest"
  installed: true

stg_nfs_server_subsystem:
  enabled: false
  status: "stopped"

stg_nfs_server_firewall:
  zone: "public"

stg_nfs_server_exports: []
...
