---
- name: "Storage / NFS / Client / Initialize"
  ansible.builtin.include_tasks:
    file: "stg_nfs_client_initialize.yml"

- name: "Storage / NFS / Client / Prepare"
  ansible.builtin.include_tasks:
    file: "stg_nfs_client_prepare.yml"
  when:
    - stg_nfs_client['prepare'] is defined
    - stg_nfs_client['prepare']

- name: "Storage / NFS / Client / Deploy"
  ansible.builtin.include_tasks:
    file: "stg_nfs_client_deploy.yml"
  when:
    - stg_nfs_client['deploy'] is defined
    - stg_nfs_client['deploy']

- name: "Storage / NFS / Client / Provision"
  ansible.builtin.include_tasks:
    file: "stg_nfs_client_provision.yml"
  when:
    - stg_nfs_client['provision'] is defined
    - stg_nfs_client['provision']

- name: "Storage / NFS / Client / Finalize"
  ansible.builtin.include_tasks:
    file: "stg_nfs_client_finalize.yml"
...
