---
- name: "Storage / NFS / Client / Initialize / Check Platform compatibility"
  ansible.builtin.assert:
    quiet: true
    fail_msg: "Target Platform not supported: {{ ansible_distribution + ansible_distribution_major_version }}"
    that:
      - ansible_distribution + ansible_distribution_major_version in stg_nfs_client_platforms

- name: "Storage / NFS / Client / Initialize / Check required parameters: Prepare,Provision"
  ansible.builtin.assert:
    fail_msg: "Required end-state parameters are missing ({{ stg_nfs_client_paths }})"
    quiet: true
    that:
      - stg_nfs_client_paths['shares_root'] is defined
      - stg_nfs_client_paths['shares_root'] | length > 0
  when:
    - (stg_nfs_client['prepare'] is defined and stg_nfs_client['prepare']) or
      (stg_nfs_client['provision'] is defined and stg_nfs_client['provision'])

- name: "Storage / NFS / Client / Initialize / Set Platform specific variables"
  ansible.builtin.include_vars:
    file: "{{ 'platform-' + stg_nfs_client_os_family + '.yml' }}"

- name: "Storage / NFS / Client / Initialize / Resolve prerequisites"
  ansible.builtin.include_tasks:
    file: "stg_nfs_client_prerequisite.yml"
  when:
    - "'resolve_prereq' in stg_nfs_client"
    - stg_nfs_client['resolve_prereq']
...
