---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "stg_autofs"

    - name: "Identify service status"
      ansible.builtin.command:
        argv:
          - "systemctl"
          - "is-enabled"
          - "{{ stg_autofs_subsystems['service'] }}"
      changed_when: false
      register: result

    - name: "Check that the service is active"
      ansible.builtin.assert:
        that:
          - result['stdout_lines'] is search( 'enabled' )

    - name: "Detect target path"
      ansible.builtin.stat:
        path: "{{ stg_autofs_base['etc']['autofs_conf'] }}"
      register: file_stat

    - name: "Verify path is created"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
