---
galaxy_info:
  role_name: "stg_repository"
  author: "serdigital64"
  description: "Manage file repositories provisioning"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "repository"
dependencies: []
...
