---
- name: "Storage / Repository / Initialize"
  ansible.builtin.include_tasks:
    file: "stg_repository_initialize.yml"

- name: "Storage / Repository / Prepare"
  ansible.builtin.include_tasks:
    file: "stg_repository_prepare.yml"
  when:
    - stg_repository['prepare'] is defined
    - stg_repository['prepare']

- name: "Storage / Repository / Provision"
  ansible.builtin.include_tasks:
    file: "stg_repository_provision.yml"
  when:
    - stg_repository['provision'] is defined
    - stg_repository['provision']

- name: "Storage / Repository / Finalize"
  ansible.builtin.include_tasks:
    file: "stg_repository_finalize.yml"
...
