---
- name: "Storage / Repository / Provision / Shares / Create"
  become: true
  ansible.builtin.file:
    follow: false
    force: false
    unsafe_writes: false
    recurse: false
    state: "directory"
    path: "{{ stg_repositories_resources[stg_repository___provision_share]['path'] }}"
    owner: "{{ stg_repositories_resources[stg_repository___provision_share]['user'] }}"
    group: "{{ stg_repositories_resources[stg_repository___provision_share]['group'] }}"
    mode: "{{ stg_repositories_resources[stg_repository___provision_share]['mode'] }}"
  loop: "{{ stg_repositories_resources | list }}"
  loop_control:
    loop_var: "stg_repository___provision_share"
...
