---
- name: "Storage / Repository / Prepare / Users / Create"
  vars:
    sys_user:
      setup: true
    sys_user_accounts: "{{ stg_repositories_users }}"
    sys_user_groups: "{{ stg_repositories_groups }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_user"
...
