---
# Define supported platforms
stg_nfs_client_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "Rocky8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Ubuntu22"
  - "Fedora33"
  - "Fedora35"
  - "Fedora36"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
stg_nfs_client_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
        ( ansible_distribution == 'AlmaLinux' ) or
        ( ansible_distribution == 'Rocky' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}
  "

# Define default options. Used as a backup for cases where optional Ansible defaults are missing
stg_nfs_client_presets: {}

# Multiplatform packages
stg_nfs_client_profiles_common:
  snap: {}
  flatpak: {}

# Define common paths
stg_nfs_client_base_common:
  paths:
    shares_root: "{{ stg_nfs_client_paths['shares_root'] }}"
  run: {}
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"

# Temporary variables
# stg_nfs_client___prepare_path
# stg_nfs_client___provision_share
...
