---
# Define platform specific paths
stg_nfs_client_base:
  paths: "{{ stg_nfs_client_base_common['paths'] }}"
  run: "{{ stg_nfs_client_base_common['run'] }}"
  access: "{{ stg_nfs_client_base_common['access'] }}"

# Define application package details
stg_nfs_client_profiles:
  snap: "{{ stg_nfs_client_profiles_common['snap'] }}"
  flatpak: "{{ stg_nfs_client_profiles_common['flatpak'] }}"
  distro:
    latest:
      supported: true
      packages:
        - name: "nfs-common"
        - name: "keyutils"
        - name: "rpcbind"

# Define custom package repositories
stg_nfs_client_repository_custom_yum: []
stg_nfs_client_repository_custom_apt: []

# Set package repositories states
stg_nfs_client_repository_catalog_distro: {}
stg_nfs_client_repository_catalog_yum: {}
stg_nfs_client_repository_catalog_apt: {}
...
