---
# Define supported platforms
stg_repository_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

# Temporary loop variables
# stg_repository___provision_share
...
