---
galaxy_info:
  role_name: "stg_nfs_client"
  author: "serdigital64"
  description: "Manage the Linux NFS client"
  company: "none"
  license: "Apache-2.0"
  min_ansible_version: "2.10"
  platforms:
    - name: "GenericLinux"
      versions:
        - "all"
    - name: "GenericUNIX"
      versions:
        - "all"
  galaxy_tags:
    - "nfs"
dependencies: []
...
